package ru.stqa.pft.sandbox;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void a() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1058, 682));
    driver.findElement(By.id("APjFqb")).sendKeys("fapl.ru");
    driver.findElement(By.cssSelector("#jZ2SBf b:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#rso > .MjjYud:nth-child(1) .LC20lb")).click();
    driver.findElement(By.linkText("\"Брайтон\" завершил приобретение Балеба")).click();
    driver.close();
  }
}
